# Generated by Django 5.2.15 on 2026-06-08 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Nom d'une icône (ex: hotel, restaurant, bar, site)",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Commune",
                "verbose_name_plural": "Communes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Etablissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("adresse", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "prix_minimum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prix indicatif le plus bas, en USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "prix_maximum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prix indicatif le plus haut, en USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=20)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("publie", "Publié"),
                            ("archive", "Archivé"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="etablissements",
                        to="listings.categorie",
                    ),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="etablissements",
                        to="listings.commune",
                    ),
                ),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        blank=True,
                        help_text="Médiateur ou gestionnaire ayant créé la fiche",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etablissements_enregistres",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proprietaire",
                    models.ForeignKey(
                        blank=True,
                        help_text="Compte du propriétaire, une fois la fiche réclamée",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etablissements_geres",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Établissement",
                "verbose_name_plural": "Établissements",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="ImageEtablissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="etablissements/%Y/%m/")),
                ("legende", models.CharField(blank=True, max_length=200)),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="listings.etablissement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
                "ordering": ["ordre", "id"],
            },
        ),
    ]
