# Generated by Django 5.2.15 on 2026-06-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="etablissement",
            name="email_contact",
            field=models.EmailField(
                blank=True,
                help_text="Email de réservation (hôtels et restaurants)",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="whatsapp_contact",
            field=models.CharField(
                blank=True,
                help_text="Numéro WhatsApp pour les réservations, ex: +243800000000 (hôtels et restaurants)",
                max_length=20,
            ),
        ),
    ]
