# Generated by Django 5.2.15 on 2026-06-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_add_email_whatsapp_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageetablissement",
            name="url_image",
            field=models.URLField(
                blank=True,
                help_text="URL d'une image hébergée ailleurs (utilisée si aucun fichier n'est uploadé)",
            ),
        ),
        migrations.AlterField(
            model_name="imageetablissement",
            name="image",
            field=models.ImageField(blank=True, upload_to="etablissements/%Y/%m/"),
        ),
    ]
