# Generated by Django 5.2.15 on 2026-06-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_add_url_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="etablissement",
            name="etoiles",
            field=models.CharField(
                blank=True, help_text="0 à 5 étoiles (vide = non classé)", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="evaluation",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Note Google (0–5)",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="facebook",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="horaires",
            field=models.TextField(blank=True, help_text="Horaires d'ouverture"),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="nombre_avis",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="nombre_chambres",
            field=models.CharField(blank=True, help_text="Ex: 65+, 24", max_length=50),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="services",
            field=models.TextField(
                blank=True,
                help_text="Services séparés par des virgules (Wi-Fi, Parking…)",
            ),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="site_web",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="tiktok",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="etablissement",
            name="type_cuisine",
            field=models.CharField(
                blank=True,
                help_text="Congolaise, Italienne, Asiatique…",
                max_length=100,
            ),
        ),
    ]
