# Generated by Django 5.2.15 on 2026-06-08 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_prevue", models.DateTimeField()),
                ("nombre_personnes", models.PositiveIntegerField(default=1)),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("en_ligne", "Payer en ligne (Mobile Money)"),
                            ("sur_place", "Payer sur place"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de confirmation"),
                            ("confirmee", "Confirmée"),
                            ("terminee", "Terminée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="listings.etablissement",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "operateur",
                    models.CharField(
                        choices=[
                            ("mpesa", "M-Pesa"),
                            ("airtel_money", "Airtel Money"),
                            ("orange_money", "Orange Money"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference_transaction", models.CharField(blank=True, max_length=100)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("bloque", "Bloqué sur la plateforme"),
                            ("libere", "Reversé à l'établissement"),
                            ("rembourse", "Remboursé au client"),
                        ],
                        default="bloque",
                        max_length=20,
                    ),
                ),
                (
                    "confirme_par_client",
                    models.BooleanField(
                        default=False,
                        verbose_name="Le client confirme être arrivé sur place",
                    ),
                ),
                (
                    "confirme_par_etablissement",
                    models.BooleanField(
                        default=False,
                        verbose_name="L'établissement confirme la présence du client",
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("libere_le", models.DateTimeField(blank=True, null=True)),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiement",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-cree_le"],
            },
        ),
    ]
