# Generated by Django 5.2.15 on 2026-06-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbonnementNewsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Abonnement newsletter",
                "verbose_name_plural": "Abonnements newsletter",
                "ordering": ["-cree_le"],
            },
        ),
    ]
