# Generated by Django 5.2.15 on 2026-06-08 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="abonnementnewsletter",
            name="numero_whatsapp",
            field=models.CharField(
                blank=True,
                help_text="Numéro au format international, ex: +243800000000 (optionnel)",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Annonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=150)),
                ("message", models.TextField()),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("envoyee_le", models.DateTimeField(blank=True, null=True)),
                ("nombre_emails_envoyes", models.PositiveIntegerField(default=0)),
                ("nombre_whatsapp_envoyes", models.PositiveIntegerField(default=0)),
                (
                    "creee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "etablissement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Établissement concerné (optionnel)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="annonces",
                        to="listings.etablissement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annonce",
                "verbose_name_plural": "Annonces",
                "ordering": ["-cree_le"],
            },
        ),
    ]
